# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vedalken
email: contact.matteomazzola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mining Pauper one alghoritm at time.
baseurl: "/"
url: "vedalken.cloud"
twitter_username: chumpblocckami
github_username:  chumpblocckami
image: https://cards.scryfall.io/art_crop/front/2/c/2c3bbbe9-91a3-4da5-a1b4-6aed4bd684de.jpg?1651655793

# Build settings
theme: minima
plugins:
  - jekyll-feed
